#!/usr/bin/env bash

add_repo() {
sudo echo "deb http://http.us.debian.org/debian wheezy main contrib non-free # wheezy #" >> /etc/apt/sources.list
}

edit_config() {
cat << EOF >> /etc/pimd.conf
phyint eth0 disable
cand_rp time 30 priority 20
cand_bootstrap_router priority 5
group_prefix 224.0.0.0 masklen 4
switch_data_threshold		rate 50000 interval 20
switch_register_threshold	rate 50000 interval 20
EOF
}

main() {
add_repo
apt-get update
apt-get install pimd
service pimd stop
edit_config
service pimd start

pimd -r
}

main "$@"
