#!/usr/bin/env bash

add_repo() {
echo "deb http://http.us.debian.org/debian wheezy main contrib non-free # wheezy #" >> /etc/apt/sources.list
}

edit_config() {
sed -i 's/#phyint de1 disable/phyint eth0 disable/g' /etc/pimd.conf
}

main() {
add_repo
apt-get update
apt-get install pimd
service pimd stop
edit_config
service pimd start

pimd -r
}

main "$@"
